name: makefile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install APT deps
      run: sudo apt install gcc make gcc-arm-none-eabi curl

    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        rustup target add armv5te-unknown-linux-musleabi

    - name: Compile xa2_130
      run: cd src && make hack.bin model=xa2_130
